name: Deploy Website when Merge on development or main

on:
  push:
    branches: 
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build_website
        with:
          node-version: lts/iron
          artifact-name: website_deployment

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: website_deployment
          path: dist
      - name: List files
        run: ls -la
      - name: List files build
        run: ls -la dist
      - name: Setup SSH
        env:
          PRIV_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          mkdir ~/.ssh
          echo "$PRIV_KEY" >> ~/.ssh/key
          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/key
      - name: Deploy Development
        if: github.head_ref == 'development'
        run: scp -i ~/.ssh/key -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.DEPLOY_DIR_DEV }}
      - name: Deploy Production
        if: github.head_ref == 'main'
        run: scp -i ~/.ssh/key -r dist/* ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.DEPLOY_DIR_PROD }}

